export type Oeuvre = {
        _id: string | number,
        title: string,
        description: string,
        category: string,
        subCategory: string,
        illustration?: string[],
        video?: string,
        postDate: Date,
        releaseDate?: Date,
        isMediaTypeImages: boolean,
        author: string,
        plateforme?: string,
        likeCount: number,
        otherFields?: {
            genre?: string[],
            artiste?: string,
            realistateur?: string,
            developpeur?: string,
            editeur?: string,
            compositeur?: string,
            scenariste?: string,
            producteur?: string,
            acteurs?: string[],
        },
    };