name: Build & publish to Github Registry

on:
    push:
        branches: ["main"]

jobs:
    push_to_registry:
        name: Push Docker image to Github Registry
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ghcr.io/artlas/web:prod

            - name: "Reload docker on server"
              run: |
                  pip3 install google-auth
                  export IAP_CLIENT_ID=${{ secrets.IAP_CLIENT_ID }}
                  export GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GCP_SERVICE_ACCOUNT}}
                  python3 reload_request.py artlas-production prod
