name: Build & publish docker

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    push_to_registry:
        name: Push Docker image to Github Registry
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              if: github.event_name != 'pull_request'
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Extract metadata (tags, labels) for Docker
              if: github.event_name != 'pull_request'
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ghcr.io/Artlas/web

            - name: Build and push Docker image
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
